spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: admin
        password: 123    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    jackson:
        default-property-inclusion: non_empty
        serialization:
            indent-output: true
            
logging:
  level:
    root: INFO
    com.cyb.spring.jpa.demo: DEBUG