version: '3'
services:
  jpa-demo:
    container_name: jpa-demo
    image: hustcyb/cyb-spring-boot-jpa-demo:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
        - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=test
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d