USE `test`;

DROP TABLE IF EXISTS `student`;

CREATE TABLE `student` (
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '编号',
	`name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '姓名',
	`age` INT NOT NULL COMMENT '年龄',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '学生';